name: PlayerVaults
version: '${project.version}'
main: me.sourceform.vaults.Vaults
api-version: '1.20'
authors: [SourceForm]
description: Simple plugin which provides players with a personal vault to store valuables
website: https://github.com/SourceForm
commands:
  playervault:
    description: Opens the playervault menu
    usage: /<command>
    aliases:
      - pv
permissions:
  playervaults.openvault:
    description: allows the player to use vaults
    default: op